name: diacare
description: AI-based Diabetic Health Assistant
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  uuid: ^3.0.6
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  permission_handler: ^11.3.1
  http: ^1.6.0
  intl: ^0.18.1 # Added for date formatting

  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
