name: diacare
description: AI-based Diabetic Health Assistant
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  uuid: ^3.0.6
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  http: ^1.2.0
  intl: ^0.18.1
  collection: ^1.17.0
  crypto: ^3.0.3
  dynamic_color: ^1.6.9
  table_calendar: ^3.0.9
  google_generative_ai: ^0.4.0
  pedometer: ^4.0.1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
